// Glossari CA → ES / AR / UR / UK per a la traducció per hover.
// La web és sempre en català: aquestes traduccions apareixen com a
// tooltip en passar per sobre, perquè l'alumnat nouvingut entengui
// el català sense dependre de la llengua materna.
//
// Les entrades multi-paraula tenen prioritat (es tradueix l'expressió
// sencera quan paraula per paraula no tindria sentit).

export const GLOSSARY = [
  // ── Expressions i frases fetes ──────────────────────────
  { ca: 'es marceix', es: 'se marchita', ar: 'تذبل', ur: 'مرجھا جاتا ہے', uk: "в'яне" },
  { ca: 'feina a casa', es: 'deberes', ar: 'واجب منزلي', ur: 'گھر کا کام', uk: 'домашнє завдання' },
  { ca: 'data límit', es: 'fecha límite', ar: 'الموعد النهائي', ur: 'آخری تاریخ', uk: 'останній термін' },
  { ca: 'has faltat', es: 'has faltado a clase', ar: 'تغيّبت عن الصف', ur: 'آپ غیر حاضر تھے', uk: 'ти пропустив урок' },
  { ca: 'idees prèvies', es: 'ideas previas', ar: 'أفكارك المسبقة', ur: 'پہلے سے موجود خیالات', uk: 'попередні ідеї' },
  { ca: 'exit tiquet', es: 'ticket de salida', ar: 'بطاقة الخروج', ur: 'ایگزٹ ٹکٹ (اختتامی سوال)', uk: 'вихідний квиток (підсумкове запитання)' },
  { ca: 'en parelles', es: 'en parejas', ar: 'في أزواج', ur: 'جوڑوں میں', uk: 'парами' },
  { ca: 'en veu alta', es: 'en voz alta', ar: 'بصوت عالٍ', ur: 'بلند آواز میں', uk: 'вголос' },
  { ca: 'a mà', es: 'a mano', ar: 'يدويًا', ur: 'ہاتھ سے', uk: 'від руки' },
  { ca: 'pas a pas', es: 'paso a paso', ar: 'خطوة بخطوة', ur: 'قدم بہ قدم', uk: 'крок за кроком' },
  { ca: 'per quina raó', es: 'por qué razón', ar: 'لأي سبب', ur: 'کس وجہ سے', uk: 'з якої причини' },
  { ca: 'posa en comú', es: 'puesta en común', ar: 'شاركها مع الصف', ur: 'سب کے ساتھ شیئر کریں', uk: 'поділися з класом' },
  { ca: 'membrana semipermeable', es: 'membrana semipermeable', ar: 'غشاء شبه نافذ', ur: 'نیم نفوذ پذیر جھلی', uk: 'напівпроникна мембрана' },
  { ca: 'respiració cel·lular', es: 'respiración celular', ar: 'التنفس الخلوي', ur: 'خلوی تنفس', uk: 'клітинне дихання' },
  { ca: 'divisió cel·lular', es: 'división celular', ar: 'انقسام الخلية', ur: 'خلیے کی تقسیم', uk: 'поділ клітини' },
  { ca: 'cèl·lula mare', es: 'célula madre', ar: 'الخلية الأم', ur: 'مادر خلیہ', uk: 'материнська клітина' },
  { ca: 'cèl·lules filles', es: 'células hijas', ar: 'خلايا وليدة', ur: 'بیٹی خلیے', uk: 'дочірні клітини' },
  { ca: 'cèl·lules sexuals', es: 'células sexuales', ar: 'الخلايا الجنسية', ur: 'جنسی خلیے', uk: 'статеві клітини' },
  { ca: 'freqüència cardíaca', es: 'frecuencia cardíaca', ar: 'معدل ضربات القلب', ur: 'دل کی دھڑکن کی رفتار', uk: 'частота серцевих скорочень' },
  { ca: 'doble circulació', es: 'doble circulación', ar: 'الدورة الدموية المزدوجة', ur: 'دوہری گردشِ خون', uk: 'подвійний кровообіг' },
  { ca: 'intestí prim', es: 'intestino delgado', ar: 'الأمعاء الدقيقة', ur: 'چھوٹی آنت', uk: 'тонка кишка' },
  { ca: 'intestí gros', es: 'intestino grueso', ar: 'الأمعاء الغليظة', ur: 'بڑی آنت', uk: 'товста кишка' },
  { ca: 'sistema digestiu', es: 'sistema digestivo', ar: 'الجهاز الهضمي', ur: 'نظامِ ہضم', uk: 'травна система' },
  { ca: 'sistema circulatori', es: 'sistema circulatorio', ar: 'الجهاز الدوري', ur: 'دورانِ خون کا نظام', uk: 'кровоносна система' },
  { ca: 'sistema nerviós', es: 'sistema nervioso', ar: 'الجهاز العصبي', ur: 'اعصابی نظام', uk: 'нервова система' },
  { ca: 'sistema endocrí', es: 'sistema endocrino', ar: 'جهاز الغدد الصماء', ur: 'اینڈوکرائن نظام', uk: 'ендокринна система' },
  { ca: 'sistema excretor', es: 'sistema excretor', ar: 'الجهاز الإخراجي', ur: 'اخراجی نظام', uk: 'видільна система' },
  { ca: 'medul·la espinal', es: 'médula espinal', ar: 'النخاع الشوكي', ur: 'حرام مغز', uk: 'спинний мозок' },
  { ca: 'arc reflex', es: 'arco reflejo', ar: 'القوس الانعكاسي', ur: 'اضطراری قوس', uk: 'рефлекторна дуга' },
  { ca: 'temps de reacció', es: 'tiempo de reacción', ar: 'زمن رد الفعل', ur: 'ردِعمل کا وقت', uk: 'час реакції' },
  { ca: 'àcid làctic', es: 'ácido láctico', ar: 'حمض اللاكتيك', ur: 'لیکٹک ایسڈ', uk: 'молочна кислота' },
  { ca: 'zona aeròbica', es: 'zona aeróbica', ar: 'المنطقة الهوائية', ur: 'ایروبک زون', uk: 'аеробна зона' },
  { ca: 'zona anaeròbica', es: 'zona anaeróbica', ar: 'المنطقة اللاهوائية', ur: 'اینیروبک زون', uk: 'анаеробна зона' },
  { ca: 'sèrum fisiològic', es: 'suero fisiológico', ar: 'محلول ملحي طبي', ur: 'فزیولوجیکل سیرم', uk: 'фізіологічний розчин' },
  { ca: 'aigua pura', es: 'agua pura', ar: 'ماء نقي', ur: 'خالص پانی', uk: 'чиста вода' },
  { ca: 'sense closca', es: 'sin cáscara', ar: 'بدون قشرة', ur: 'بغیر چھلکے کے', uk: 'без шкаралупи' },
  { ca: 'bolo alimentici', es: 'bolo alimenticio', ar: 'البلعة الغذائية', ur: 'نوالہ (بولس)', uk: 'харчова грудка' },
  { ca: 'vena porta', es: 'vena porta', ar: 'الوريد البابي', ur: 'پورٹل ورید', uk: 'ворітна вена' },
  { ca: 'hidrats de carboni', es: 'hidratos de carbono', ar: 'الكربوهيدرات', ur: 'کاربوہائیڈریٹس', uk: 'вуглеводи' },
  { ca: 'prova escrita', es: 'examen escrito', ar: 'اختبار كتابي', ur: 'تحریری امتحان', uk: 'письмовий екзамен' },
  { ca: 'full de treball', es: 'hoja de trabajo', ar: 'ورقة العمل', ur: 'ورک شیٹ', uk: 'робочий аркуш' },

  // ── La cèl·lula (SA1) ───────────────────────────────────
  { ca: 'cèl·lula', es: 'célula', ar: 'خلية', ur: 'خلیہ', uk: 'клітина' },
  { ca: 'cèl·lules', es: 'células', ar: 'خلايا', ur: 'خلیے', uk: 'клітини' },
  { ca: 'membrana', es: 'membrana', ar: 'غشاء', ur: 'جھلی', uk: 'мембрана' },
  { ca: 'nucli', es: 'núcleo', ar: 'نواة', ur: 'مرکزہ', uk: 'ядро' },
  { ca: 'mitocondri', es: 'mitocondria', ar: 'ميتوكوندريون', ur: 'مائٹوکونڈریا', uk: 'митохондрія' },
  { ca: 'mitocondris', es: 'mitocondrias', ar: 'ميتوكوندريا', ur: 'مائٹوکونڈریا', uk: 'митохондрії' },
  { ca: 'orgànul', es: 'orgánulo', ar: 'عضيّة', ur: 'عضوہ', uk: 'органела' },
  { ca: 'orgànuls', es: 'orgánulos', ar: 'عضيّات', ur: 'عضوے', uk: 'органели' },
  { ca: 'citoplasma', es: 'citoplasma', ar: 'سيتوبلازم', ur: 'سائٹوپلازم', uk: 'цитоплазма' },
  { ca: 'ADN', es: 'ADN', ar: 'الحمض النووي DNA', ur: 'ڈی این اے', uk: 'ДНК' },
  { ca: 'gens', es: 'genes', ar: 'جينات', ur: 'جینز', uk: 'гени' },
  { ca: 'proteïnes', es: 'proteínas', ar: 'بروتينات', ur: 'پروٹین', uk: 'білки' },
  { ca: 'teixit', es: 'tejido', ar: 'نسيج', ur: 'بافت', uk: 'тканина' },
  { ca: 'teixits', es: 'tejidos', ar: 'أنسجة', ur: 'بافتیں', uk: 'тканини' },
  { ca: 'òrgan', es: 'órgano', ar: 'عضو', ur: 'عضو', uk: 'орган' },
  { ca: 'òrgans', es: 'órganos', ar: 'أعضاء', ur: 'اعضاء', uk: 'органи' },
  { ca: 'organisme', es: 'organismo', ar: 'كائن حي', ur: 'جاندار', uk: 'організм' },
  { ca: 'procariota', es: 'procariota', ar: 'بدائية النواة', ur: 'پروکیریوٹ', uk: 'прокаріот' },
  { ca: 'eucariota', es: 'eucariota', ar: 'حقيقية النواة', ur: 'یوکیریوٹ', uk: 'еукаріот' },
  { ca: 'autòtrofs', es: 'autótrofos', ar: 'ذاتية التغذية', ur: 'خود خوراک ساز', uk: 'автотрофи' },
  { ca: 'heteròtrofs', es: 'heterótrofos', ar: 'غيرية التغذية', ur: 'غیر خود خوراک ساز', uk: 'гетеротрофи' },
  { ca: 'fotosíntesi', es: 'fotosíntesis', ar: 'التمثيل الضوئي', ur: 'ضیائی تالیف', uk: 'фотосинтез' },
  { ca: 'energia', es: 'energía', ar: 'طاقة', ur: 'توانائی', uk: 'енергія' },
  { ca: 'glucosa', es: 'glucosa', ar: 'جلوكوز', ur: 'گلوکوز', uk: 'глюкоза' },
  { ca: 'oxigen', es: 'oxígeno', ar: 'أكسجين', ur: 'آکسیجن', uk: 'кисень' },
  { ca: 'aliment', es: 'alimento', ar: 'غذاء', ur: 'خوراک', uk: 'їжа' },
  { ca: 'aliments', es: 'alimentos', ar: 'أغذية', ur: 'غذائیں', uk: 'продукти' },
  { ca: 'menjar', es: 'comer / comida', ar: 'الأكل / الطعام', ur: 'کھانا', uk: 'їсти / їжа' },
  { ca: 'respirar', es: 'respirar', ar: 'التنفس', ur: 'سانس لینا', uk: 'дихати' },
  { ca: 'osmosi', es: 'ósmosis', ar: 'التناضح (الأسموزية)', ur: 'اوسموسس', uk: 'осмос' },
  { ca: 'semipermeable', es: 'semipermeable', ar: 'شبه نافذ', ur: 'نیم نفوذ پذیر', uk: 'напівпроникний' },
  { ca: 'concentració', es: 'concentración', ar: 'تركيز', ur: 'ارتکاز', uk: 'концентрація' },
  { ca: 'solut', es: 'soluto', ar: 'مادة مذابة', ur: 'محلول مادہ', uk: 'розчинена речовина' },
  { ca: 'isotònic', es: 'isotónico', ar: 'متساوي التوتر', ur: 'آئسوٹونک', uk: 'ізотонічний' },
  { ca: 'hipertònic', es: 'hipertónico', ar: 'مفرط التوتر', ur: 'ہائپرٹونک', uk: 'гіпертонічний' },
  { ca: "s'infla", es: 'se hincha', ar: 'ينتفخ', ur: 'پھول جاتا ہے', uk: 'набрякає' },
  { ca: "s'encongeix", es: 'se encoge', ar: 'ينكمش', ur: 'سکڑ جاتا ہے', uk: 'стискається' },
  { ca: 'ou', es: 'huevo', ar: 'بيضة', ur: 'انڈا', uk: 'яйце' },
  { ca: 'vinagre', es: 'vinagre', ar: 'خل', ur: 'سرکہ', uk: 'оцет' },
  { ca: 'closca', es: 'cáscara', ar: 'قشرة', ur: 'چھلکا', uk: 'шкаралупа' },
  { ca: 'sucre', es: 'azúcar', ar: 'سكر', ur: 'چینی', uk: 'цукор' },
  { ca: 'got', es: 'vaso', ar: 'كوب', ur: 'گلاس', uk: 'склянка' },
  { ca: 'gots', es: 'vasos', ar: 'أكواب', ur: 'گلاس', uk: 'склянки' },
  { ca: 'adob', es: 'abono / fertilizante', ar: 'سماد', ur: 'کھاد', uk: 'добриво' },
  { ca: 'mitosi', es: 'mitosis', ar: 'الانقسام المتساوي', ur: 'مائٹوسس', uk: 'мітоз' },
  { ca: 'meiosi', es: 'meiosis', ar: 'الانقسام المنصّف', ur: 'مییوسس', uk: 'мейоз' },
  { ca: 'idèntiques', es: 'idénticas', ar: 'متطابقة', ur: 'بالکل ایک جیسے', uk: 'ідентичні' },
  { ca: 'meitat', es: 'mitad', ar: 'نصف', ur: 'آدھا', uk: 'половина' },
  { ca: 'espermatozoide', es: 'espermatozoide', ar: 'حيوان منوي', ur: 'سپرم', uk: 'сперматозоїд' },
  { ca: 'òvul', es: 'óvulo', ar: 'بويضة', ur: 'بیضہ', uk: 'яйцеклітина' },
  { ca: 'càncer', es: 'cáncer', ar: 'سرطان', ur: 'کینسر', uk: 'рак' },
  { ca: 'tumors', es: 'tumores', ar: 'أورام', ur: 'رسولیاں', uk: 'пухлини' },
  { ca: 'diferenciació', es: 'diferenciación', ar: 'التمايز', ur: 'تفریق', uk: 'диференціація' },
  { ca: 'ferida', es: 'herida', ar: 'جرح', ur: 'زخم', uk: 'рана' },
  { ca: 'ferides', es: 'heridas', ar: 'جروح', ur: 'زخم', uk: 'рани' },
  { ca: 'curar', es: 'curar', ar: 'شفاء', ur: 'ٹھیک کرنا', uk: 'загоювати' },
  { ca: 'créixer', es: 'crecer', ar: 'النمو', ur: 'بڑھنا', uk: 'рости' },
  { ca: 'reparar', es: 'reparar', ar: 'إصلاح', ur: 'مرمت کرنا', uk: 'відновлювати' },
  { ca: 'substituir', es: 'sustituir', ar: 'استبدال', ur: 'بدلنا', uk: 'замінювати' },
  { ca: 'neurona', es: 'neurona', ar: 'خلية عصبية', ur: 'نیوران', uk: 'нейрон' },
  { ca: 'neurones', es: 'neuronas', ar: 'خلايا عصبية', ur: 'نیورانز', uk: 'нейрони' },
  { ca: 'pell', es: 'piel', ar: 'جلد', ur: 'جلد', uk: 'шкіра' },
  { ca: 'múscul', es: 'músculo', ar: 'عضلة', ur: 'پٹھا', uk: "м'яз" },
  { ca: 'músculs', es: 'músculos', ar: 'عضلات', ur: 'پٹھے', uk: "м'язи" },
  { ca: 'muscular', es: 'muscular', ar: 'عضلي', ur: 'عضلاتی', uk: "м'язовий" },

  // ── El cos humà (SA2) ───────────────────────────────────
  { ca: 'nutrients', es: 'nutrientes', ar: 'مغذيات', ur: 'غذائی اجزاء', uk: 'поживні речовини' },
  { ca: 'nutrient', es: 'nutriente', ar: 'مادة مغذية', ur: 'غذائی جز', uk: 'поживна речовина' },
  { ca: 'midó', es: 'almidón', ar: 'نشا', ur: 'نشاستہ', uk: 'крохмаль' },
  { ca: 'greixos', es: 'grasas', ar: 'دهون', ur: 'چکنائیاں', uk: 'жири' },
  { ca: 'fosfolípids', es: 'fosfolípidos', ar: 'فوسفوليبيدات', ur: 'فاسفولپڈز', uk: 'фосфоліпіди' },
  { ca: 'aminoàcids', es: 'aminoácidos', ar: 'أحماض أمينية', ur: 'امینو ایسڈز', uk: 'амінокислоти' },
  { ca: 'vitamines', es: 'vitaminas', ar: 'فيتامينات', ur: 'وٹامنز', uk: 'вітаміни' },
  { ca: 'ferro', es: 'hierro', ar: 'حديد', ur: 'فولاد (آئرن)', uk: 'залізо' },
  { ca: 'hemoglobina', es: 'hemoglobina', ar: 'هيموجلوبين', ur: 'ہیموگلوبن', uk: 'гемоглобін' },
  { ca: 'sang', es: 'sangre', ar: 'دم', ur: 'خون', uk: 'кров' },
  { ca: 'plasma', es: 'plasma', ar: 'بلازما', ur: 'پلازما', uk: 'плазма' },
  { ca: 'eritròcits', es: 'glóbulos rojos', ar: 'كريات الدم الحمراء', ur: 'سرخ خونی خلیے', uk: "червоні кров'яні тільця" },
  { ca: 'leucòcits', es: 'glóbulos blancos', ar: 'كريات الدم البيضاء', ur: 'سفید خونی خلیے', uk: "білі кров'яні тільця" },
  { ca: 'plaquetes', es: 'plaquetas', ar: 'صفائح دموية', ur: 'پلیٹلیٹس', uk: 'тромбоцити' },
  { ca: 'anèmia', es: 'anemia', ar: 'فقر الدم', ur: 'خون کی کمی', uk: 'анемія' },
  { ca: 'analítica', es: 'análisis de sangre', ar: 'تحليل الدم', ur: 'خون کا ٹیسٹ', uk: 'аналіз крові' },
  { ca: 'hematòcrit', es: 'hematocrito', ar: 'الهيماتوكريت', ur: 'ہیماٹوکرٹ', uk: 'гематокрит' },
  { ca: 'digestió', es: 'digestión', ar: 'الهضم', ur: 'ہضم', uk: 'травлення' },
  { ca: 'estómac', es: 'estómago', ar: 'معدة', ur: 'معدہ', uk: 'шлунок' },
  { ca: 'esòfag', es: 'esófago', ar: 'مريء', ur: 'غذائی نالی', uk: 'стравохід' },
  { ca: 'pàncrees', es: 'páncreas', ar: 'بنكرياس', ur: 'لبلبہ', uk: 'підшлункова залоза' },
  { ca: 'bilis', es: 'bilis', ar: 'الصفراء', ur: 'صفرا', uk: 'жовч' },
  { ca: 'enzims', es: 'enzimas', ar: 'إنزيمات', ur: 'خامرے (انزائمز)', uk: 'ферменти' },
  { ca: 'àcid', es: 'ácido', ar: 'حمض', ur: 'تیزاب', uk: 'кислота' },
  { ca: 'bicarbonat', es: 'bicarbonato', ar: 'بيكربونات', ur: 'بائی کاربونیٹ', uk: 'бікарбонат' },
  { ca: 'quimo', es: 'quimo', ar: 'الكيموس', ur: 'کائم', uk: 'хімус' },
  { ca: 'peristaltisme', es: 'peristaltismo', ar: 'الحركة الدودية', ur: 'پیرسٹالسس', uk: 'перистальтика' },
  { ca: 'vellositats', es: 'vellosidades', ar: 'زغابات معوية', ur: 'آنتوں کے ریشے', uk: 'ворсинки' },
  { ca: 'absorció', es: 'absorción', ar: 'امتصاص', ur: 'جذب', uk: 'всмоктування' },
  { ca: 'microbiota', es: 'microbiota', ar: 'الميكروبيوم المعوي', ur: 'مائکروبایوٹا', uk: 'мікробіота' },
  { ca: 'bacteris', es: 'bacterias', ar: 'بكتيريا', ur: 'بیکٹیریا', uk: 'бактерії' },
  { ca: 'cor', es: 'corazón', ar: 'قلب', ur: 'دل', uk: 'серце' },
  { ca: 'aurícules', es: 'aurículas', ar: 'أذينان', ur: 'ایٹریا (بالائی خانے)', uk: 'передсердя' },
  { ca: 'ventricles', es: 'ventrículos', ar: 'بطينان', ur: 'وینٹریکلز (زیریں خانے)', uk: 'шлуночки' },
  { ca: 'ventricle', es: 'ventrículo', ar: 'بطين', ur: 'وینٹریکل', uk: 'шлуночок' },
  { ca: 'vàlvules', es: 'válvulas', ar: 'صمامات', ur: 'والوز', uk: 'клапани' },
  { ca: 'tabi', es: 'tabique', ar: 'حاجز', ur: 'پردہ (سیپٹم)', uk: 'перегородка' },
  { ca: 'artèria', es: 'arteria', ar: 'شريان', ur: 'شریان', uk: 'артерія' },
  { ca: 'artèries', es: 'arterias', ar: 'شرايين', ur: 'شریانیں', uk: 'артерії' },
  { ca: 'vena', es: 'vena', ar: 'وريد', ur: 'ورید', uk: 'вена' },
  { ca: 'venes', es: 'venas', ar: 'أوردة', ur: 'وریدیں', uk: 'вени' },
  { ca: 'capil·lars', es: 'capilares', ar: 'شعيرات دموية', ur: 'کیپلریز', uk: 'капіляри' },
  { ca: 'aorta', es: 'aorta', ar: 'الشريان الأبهر', ur: 'شہ رگ', uk: 'аорта' },
  { ca: 'coronàries', es: 'coronarias', ar: 'الشرايين التاجية', ur: 'کورونری شریانیں', uk: 'коронарні артерії' },
  { ca: 'miocardi', es: 'miocardio', ar: 'عضلة القلب', ur: 'دل کا پٹھا', uk: 'міокард' },
  { ca: 'infart', es: 'infarto', ar: 'احتشاء (نوبة قلبية)', ur: 'ہارٹ اٹیک', uk: 'інфаркт' },
  { ca: 'batec', es: 'latido', ar: 'نبضة', ur: 'دھڑکن', uk: 'удар серця' },
  { ca: 'batecs', es: 'latidos', ar: 'نبضات', ur: 'دھڑکنیں', uk: 'удари серця' },
  { ca: 'pols', es: 'pulso', ar: 'النبض', ur: 'نبض', uk: 'пульс' },
  { ca: 'canell', es: 'muñeca', ar: 'معصم', ur: 'کلائی', uk: "зап'ясток" },
  { ca: 'pulmons', es: 'pulmones', ar: 'رئتان', ur: 'پھیپھڑے', uk: 'легені' },
  { ca: 'alvèols', es: 'alvéolos', ar: 'حويصلات هوائية', ur: 'ہوائی خانے (الویولائی)', uk: 'альвеоли' },
  { ca: 'alvèol', es: 'alvéolo', ar: 'حويصلة هوائية', ur: 'ہوائی خانہ', uk: 'альвеола' },
  { ca: 'hormona', es: 'hormona', ar: 'هرمون', ur: 'ہارمون', uk: 'гормон' },
  { ca: 'hormones', es: 'hormonas', ar: 'هرمونات', ur: 'ہارمونز', uk: 'гормони' },
  { ca: 'adrenalina', es: 'adrenalina', ar: 'أدرينالين', ur: 'ایڈرینالین', uk: 'адреналін' },
  { ca: 'insulina', es: 'insulina', ar: 'إنسولين', ur: 'انسولین', uk: 'інсулін' },
  { ca: 'glàndula', es: 'glándula', ar: 'غدة', ur: 'غدود', uk: 'залоза' },
  { ca: 'ronyó', es: 'riñón', ar: 'كلية', ur: 'گردہ', uk: 'нирка' },
  { ca: 'ronyons', es: 'riñones', ar: 'كليتان', ur: 'گردے', uk: 'нирки' },
  { ca: 'orina', es: 'orina', ar: 'بول', ur: 'پیشاب', uk: 'сеча' },
  { ca: 'urea', es: 'urea', ar: 'يوريا', ur: 'یوریا', uk: 'сечовина' },
  { ca: 'homeòstasi', es: 'homeostasis', ar: 'الاتزان الداخلي', ur: 'ہومیوسٹیسس', uk: 'гомеостаз' },
  { ca: 'nervi', es: 'nervio', ar: 'عصب', ur: 'عصب', uk: 'нерв' },
  { ca: 'nervis', es: 'nervios', ar: 'أعصاب', ur: 'اعصاب', uk: 'нерви' },
  { ca: 'reflex', es: 'reflejo', ar: 'منعكس', ur: 'اضطراری حرکت', uk: 'рефлекс' },
  { ca: 'cervell', es: 'cerebro', ar: 'دماغ', ur: 'دماغ', uk: 'мозок' },
  { ca: 'fatiga', es: 'fatiga / cansancio', ar: 'تعب', ur: 'تھکاوٹ', uk: 'втома' },
  { ca: 'esforç', es: 'esfuerzo', ar: 'جهد', ur: 'محنت / زور', uk: 'зусилля' },
  { ca: 'exercici', es: 'ejercicio', ar: 'تمرين', ur: 'ورزش', uk: 'вправа' },
  { ca: 'repòs', es: 'reposo', ar: 'راحة', ur: 'آرام', uk: 'відпочинок' },
  { ca: 'corredor', es: 'corredor', ar: 'عدّاء', ur: 'دوڑنے والا', uk: 'бігун' },
  { ca: 'corredora', es: 'corredora', ar: 'عدّاءة', ur: 'دوڑنے والی', uk: 'бігунка' },
  { ca: 'cursa', es: 'carrera', ar: 'سباق', ur: 'دوڑ', uk: 'забіг' },
  { ca: 'residus', es: 'residuos', ar: 'فضلات', ur: 'فضلہ', uk: 'відходи' },

  // ── Instruccions i vocabulari escolar ───────────────────
  { ca: 'observa', es: 'observa', ar: 'لاحظ', ur: 'مشاہدہ کریں', uk: 'спостерігай' },
  { ca: 'mesura', es: 'mide', ar: 'قِس', ur: 'ناپیں', uk: 'вимірюй' },
  { ca: 'pesa', es: 'pesa', ar: 'زِن', ur: 'وزن کریں', uk: 'зважуй' },
  { ca: 'anota', es: 'anota', ar: 'دوّن', ur: 'لکھ لیں', uk: 'запиши' },
  { ca: 'registra', es: 'registra', ar: 'سجّل', ur: 'درج کریں', uk: 'зафіксуй' },
  { ca: 'dibuixa', es: 'dibuja', ar: 'ارسم', ur: 'بنائیں (ڈرائنگ)', uk: 'намалюй' },
  { ca: 'escriu', es: 'escribe', ar: 'اكتب', ur: 'لکھیں', uk: 'напиши' },
  { ca: 'llegeix', es: 'lee', ar: 'اقرأ', ur: 'پڑھیں', uk: 'прочитай' },
  { ca: 'explica', es: 'explica', ar: 'اشرح', ur: 'وضاحت کریں', uk: 'поясни' },
  { ca: 'justifica', es: 'justifica', ar: 'برّر', ur: 'دلیل دیں', uk: 'обґрунтуй' },
  { ca: 'compara', es: 'compara', ar: 'قارن', ur: 'موازنہ کریں', uk: 'порівняй' },
  { ca: 'ordena', es: 'ordena', ar: 'رتّب', ur: 'ترتیب دیں', uk: 'впорядкуй' },
  { ca: 'classifica', es: 'clasifica', ar: 'صنّف', ur: 'درجہ بندی کریں', uk: 'класифікуй' },
  { ca: 'omple', es: 'rellena', ar: 'املأ', ur: 'بھریں', uk: 'заповни' },
  { ca: 'descarrega', es: 'descarga', ar: 'حمّل', ur: 'ڈاؤن لوڈ کریں', uk: 'завантаж' },
  { ca: 'comprova', es: 'comprueba', ar: 'تحقق', ur: 'جانچیں', uk: 'перевір' },
  { ca: 'tria', es: 'elige', ar: 'اختر', ur: 'منتخب کریں', uk: 'вибери' },
  { ca: 'marca', es: 'marca', ar: 'علّم', ur: 'نشان لگائیں', uk: 'познач' },
  { ca: 'predicció', es: 'predicción', ar: 'توقع', ur: 'پیشگوئی', uk: 'прогноз' },
  { ca: 'prediccions', es: 'predicciones', ar: 'توقعات', ur: 'پیشگوئیاں', uk: 'прогнози' },
  { ca: 'hipòtesi', es: 'hipótesis', ar: 'فرضية', ur: 'مفروضہ', uk: 'гіпотеза' },
  { ca: 'hipòtesis', es: 'hipótesis', ar: 'فرضيات', ur: 'مفروضے', uk: 'гіпотези' },
  { ca: 'resultats', es: 'resultados', ar: 'نتائج', ur: 'نتائج', uk: 'результати' },
  { ca: 'taula', es: 'tabla', ar: 'جدول', ur: 'جدول', uk: 'таблиця' },
  { ca: 'gràfica', es: 'gráfica', ar: 'رسم بياني', ur: 'گراف', uk: 'графік' },
  { ca: 'gràfiques', es: 'gráficas', ar: 'رسوم بيانية', ur: 'گراف', uk: 'графіки' },
  { ca: 'fitxa', es: 'ficha', ar: 'ورقة العمل', ur: 'ورک شیٹ', uk: 'картка' },
  { ca: 'full', es: 'hoja', ar: 'ورقة', ur: 'کاغذ / شیٹ', uk: 'аркуш' },
  { ca: 'apartat', es: 'apartado', ar: 'قسم', ur: 'حصہ', uk: 'розділ' },
  { ca: 'apartats', es: 'apartados', ar: 'أقسام', ur: 'حصے', uk: 'розділи' },
  { ca: 'pista', es: 'pista', ar: 'تلميح', ur: 'اشارہ', uk: 'підказка' },
  { ca: 'pistes', es: 'pistas', ar: 'تلميحات', ur: 'اشارے', uk: 'підказки' },
  { ca: 'pregunta', es: 'pregunta', ar: 'سؤال', ur: 'سوال', uk: 'питання' },
  { ca: 'preguntes', es: 'preguntas', ar: 'أسئلة', ur: 'سوالات', uk: 'питання' },
  { ca: 'resposta', es: 'respuesta', ar: 'إجابة', ur: 'جواب', uk: 'відповідь' },
  { ca: 'respostes', es: 'respuestas', ar: 'إجابات', ur: 'جوابات', uk: 'відповіді' },
  { ca: 'deures', es: 'deberes', ar: 'واجبات', ur: 'ہوم ورک', uk: 'домашнє завдання' },
  { ca: 'termini', es: 'plazo', ar: 'مهلة', ur: 'مدت', uk: 'термін' },
  { ca: 'entrega', es: 'entrega', ar: 'تسليم', ur: 'جمع کرانا', uk: 'здача' },
  { ca: 'entregues', es: 'entregas', ar: 'تسليمات', ur: 'جمع کرانے کی چیزیں', uk: 'здані завдання' },
  { ca: 'sessió', es: 'sesión', ar: 'حصة', ur: 'سیشن', uk: 'заняття' },
  { ca: 'sessions', es: 'sesiones', ar: 'حصص', ur: 'سیشنز', uk: 'заняття' },
  { ca: 'prova', es: 'examen', ar: 'اختبار', ur: 'امتحان', uk: 'екзамен' },
  { ca: 'rúbrica', es: 'rúbrica', ar: 'سلم التقييم', ur: 'روبرک (جانچ پیمانہ)', uk: 'рубрика оцінювання' },
  { ca: 'pòster', es: 'póster', ar: 'ملصق', ur: 'پوسٹر', uk: 'плакат' },
  { ca: 'grup', es: 'grupo', ar: 'مجموعة', ur: 'گروپ', uk: 'група' },
  { ca: 'materials', es: 'materiales', ar: 'أدوات', ur: 'سامان', uk: 'матеріали' },
  { ca: 'durada', es: 'duración', ar: 'مدة', ur: 'دورانیہ', uk: 'тривалість' },
  { ca: 'objectius', es: 'objetivos', ar: 'أهداف', ur: 'مقاصد', uk: 'цілі' },
  { ca: 'competències', es: 'competencias', ar: 'كفاءات', ur: 'صلاحیتیں', uk: 'компетентності' },
  { ca: 'recuperació', es: 'recuperación', ar: 'استدراك / تعويض', ur: 'تلافی', uk: 'відпрацювання' },
  { ca: 'autoavaluació', es: 'autoevaluación', ar: 'تقييم ذاتي', ur: 'خود تشخیص', uk: 'самооцінювання' },
  { ca: 'reflexió', es: 'reflexión', ar: 'تأمل', ur: 'غور و فکر', uk: 'рефлексія' },
  { ca: 'repte', es: 'reto', ar: 'تحدٍّ', ur: 'چیلنج', uk: 'виклик' },
  { ca: 'enigma', es: 'enigma', ar: 'لغز', ur: 'پہیلی', uk: 'загадка' },
  { ca: 'enigmes', es: 'enigmas', ar: 'ألغاز', ur: 'پہیلیاں', uk: 'загадки' },
  { ca: 'maqueta', es: 'maqueta', ar: 'مجسّم', ur: 'ماڈل', uk: 'макет' },
  { ca: 'dies', es: 'días', ar: 'أيام', ur: 'دن', uk: 'дні' },
  { ca: 'setmanes', es: 'semanas', ar: 'أسابيع', ur: 'ہفتے', uk: 'тижні' },
  { ca: 'queden', es: 'quedan / faltan', ar: 'تبقّى', ur: 'باقی ہیں', uk: 'залишається' }
]

// Índex: frases multi-paraula primer (més llargues primer), després paraules soltes
const normalize = (s) => s.toLowerCase()

export const PHRASES = GLOSSARY.filter((e) => e.ca.includes(' '))
  .sort((a, b) => b.ca.split(' ').length - a.ca.split(' ').length)
  .map((e) => ({ ...e, words: normalize(e.ca).split(' ') }))

export const WORDS = new Map(
  GLOSSARY.filter((e) => !e.ca.includes(' ')).map((e) => [normalize(e.ca), e])
)

export const MAX_PHRASE_LEN = PHRASES.length
  ? Math.max(...PHRASES.map((p) => p.words.length))
  : 1
